class PyIdentifier:
    def __init__(self, namespace: tuple[str, ...], name: str): ...
    @staticmethod
    def from_sql(input: str, normalize: bool): ...
    def eq(self, other: PyIdentifier) -> bool: ...
    def getitem(self, index: int) -> str: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
