from daft.daft import PyRecordBatch

DAFT_DASHBOARD_ENV_ENABLED: str
DAFT_DASHBOARD_ENV_NAME: str

class ConnectionHandle:
    def shutdown(self, noop_if_shutdown: bool) -> None: ...
    def get_port(self) -> int: ...

def launch(detach: bool = False, noop_if_initialized: bool = False) -> ConnectionHandle: ...
def get_dashboard_url() -> str | None: ...
def get_dashboard_queries_url() -> str | None: ...
def register_dataframe_for_display(record_batch: PyRecordBatch) -> str: ...
def generate_interactive_html(df_id: str) -> str: ...
