FROM golang:1.18-buster AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY cmd/runtime /app/build
RUN go build -o /app/entrypoint /app/build/main.go

FROM debian:buster

RUN apt-get update && \
    apt-get install ca-certificates -y && \
    apt-get install vim -y

WORKDIR /app
COPY --from=build /app/entrypoint /app/entrypoint
ENTRYPOINT /app/entrypoint
