FROM golang:1.18-buster AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY cmd/reader /app/build
RUN go build -o /app/entrypoint /app/build/main.go

FROM debian:buster

WORKDIR /app
COPY --from=build /app/entrypoint /app/entrypoint
ENTRYPOINT /app/entrypoint
