FROM python:3.8-slim-buster
RUN pip install --upgrade pip
RUN pip install fastapi uvicorn pyjwt[crypto] requests kubernetes_asyncio tenacity
COPY ./backend /app
WORKDIR /app
EXPOSE 80
ENV PYTHONPATH /app
ENTRYPOINT ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
