FROM node:16.16.0-alpine

WORKDIR /app
RUN npm install -g serve

COPY frontend/package* .
RUN npm install

ARG env
COPY frontend/src ./src
COPY frontend/public ./public
COPY frontend/tsconfig.json ./tsconfig.json

RUN if [[ "$env" = "prod" ]] ; then npm run build_prod ; else npm run build_dev ; fi

CMD serve -s build
