FROM public.ecr.aws/docker/library/python:3.9.17-slim

WORKDIR /code

COPY ./retry_server/retry-server-requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./retry_server /code/app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
