"""Tests reading Variant parquet fixtures produced by PySpark 4.0 and Daft.

Fixtures:
- tests/assets/parquet-data/spark-variant.parquet: generated by
  scripts/generate_variant_fixture.py using Spark 4.0.0 via Docker.
- tests/assets/parquet-data/daft-variant.parquet: generated by Daft's
  variant_parse_json, validated readable by Spark 4.0.0.

Both contain 10 rows with various JSON structures encoded as Variant.
"""

from __future__ import annotations

import os

import daft
from daft import DataType, col

SPARK_FIXTURE = os.path.join(os.path.dirname(__file__), "..", "assets", "parquet-data", "spark-variant.parquet")
DAFT_FIXTURE = os.path.join(os.path.dirname(__file__), "..", "assets", "parquet-data", "daft-variant.parquet")


# --- Spark-written fixture tests ---


def test_spark_fixture_schema():
    schema = daft.read_parquet(SPARK_FIXTURE).schema()
    assert schema["variant_col"].dtype == DataType.variant()
    assert schema["variant_col"].dtype.is_variant()
    assert schema["id"].dtype == DataType.string()


def test_spark_fixture_row_count():
    assert len(daft.read_parquet(SPARK_FIXTURE).collect()) == 10


def test_spark_fixture_to_json():
    result = (
        daft.read_parquet(SPARK_FIXTURE)
        .with_column("json", col("variant_col").variant_to_json())
        .select("id", "json")
        .collect()
    )
    rows = result.to_pydict()
    id_to_json = dict(zip(rows["id"], rows["json"]))

    assert '"Alice"' in id_to_json["object"]
    assert '"scores"' in id_to_json["object"]
    assert "[]" == id_to_json["empty_array"]
    assert "{}" == id_to_json["empty_object"]
    assert '"hello"' == id_to_json["string_val"]
    assert "42" == id_to_json["number_val"]
    assert "true" == id_to_json["bool_val"]
    assert "null" == id_to_json["null_val"]


def test_spark_fixture_get_field():
    result = (
        daft.read_parquet(SPARK_FIXTURE)
        .with_column("name", col("variant_col").variant_get("name"))
        .select("id", "name")
        .collect()
    )
    rows = result.to_pydict()
    id_to_name = dict(zip(rows["id"], rows["name"]))

    assert id_to_name["object"] == '"Alice"'
    assert id_to_name["nested"] is None
    assert id_to_name["array"] is None


def test_spark_fixture_get_nested_path():
    result = (
        daft.read_parquet(SPARK_FIXTURE)
        .with_column("city", col("variant_col").variant_get("user.address.city"))
        .select("id", "city")
        .collect()
    )
    rows = result.to_pydict()
    id_to_city = dict(zip(rows["id"], rows["city"]))

    assert id_to_city["nested"] == '"NYC"'
    assert id_to_city["object"] is None


def test_spark_fixture_roundtrip(tmp_path):
    """Read Spark fixture, write from Daft, read back."""
    from daft.context import execution_config_ctx

    original = daft.read_parquet(SPARK_FIXTURE)
    with execution_config_ctx(native_parquet_writer=True):
        original.write_parquet(str(tmp_path))
        read_back = daft.read_parquet(str(tmp_path)).collect()

    assert read_back.schema()["variant_col"].dtype.is_variant()
    assert len(read_back) == 10

    original_json = (
        original.with_column("j", col("variant_col").variant_to_json()).select("j").collect().to_pydict()["j"]
    )
    roundtrip_json = (
        read_back.with_column("j", col("variant_col").variant_to_json()).select("j").collect().to_pydict()["j"]
    )
    assert original_json == roundtrip_json


# --- Daft-written fixture tests ---


def test_daft_fixture_schema():
    schema = daft.read_parquet(DAFT_FIXTURE).schema()
    assert schema["variant_col"].dtype == DataType.variant()
    assert schema["id"].dtype == DataType.string()


def test_daft_fixture_row_count():
    assert len(daft.read_parquet(DAFT_FIXTURE).collect()) == 10


def test_daft_fixture_to_json():
    result = (
        daft.read_parquet(DAFT_FIXTURE)
        .with_column("json", col("variant_col").variant_to_json())
        .select("id", "json")
        .collect()
    )
    rows = result.to_pydict()
    id_to_json = dict(zip(rows["id"], rows["json"]))

    assert '"Alice"' in id_to_json["object"]
    assert "[]" == id_to_json["empty_array"]
    assert "{}" == id_to_json["empty_object"]
    assert "42" == id_to_json["number_val"]


def test_daft_fixture_get_field():
    result = (
        daft.read_parquet(DAFT_FIXTURE)
        .with_column("name", col("variant_col").variant_get("name"))
        .select("id", "name")
        .collect()
    )
    rows = result.to_pydict()
    id_to_name = dict(zip(rows["id"], rows["name"]))

    assert id_to_name["object"] == '"Alice"'
    assert id_to_name["nested"] is None
