DAFT_DASHBOARD_ENV_NAME: str
DAFT_DASHBOARD_QUERIES_URL: str
DAFT_DASHBOARD_URL_SHUTDOWN: str

def launch(detach: bool = False, noop_if_initialized: bool = False): ...
def shutdown(noop_if_shutdown: bool = False): ...
def cli(args: list[str], static_assets_path: str): ...
