DAFT_DASHBOARD_ENV_NAME: str
DAFT_DASHBOARD_QUERIES_URL: str
DAFT_DASHBOARD_URL_SHUTDOWN: str

def launch(static_assets_path: str, detach: bool = False): ...
def shutdown(): ...
def cli(args: list[str], static_assets_path: str): ...
