/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eventualcomputing.icebridge;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appCanRun() {
        App classUnderTest = new App();
    }
}
