"""Asof-join benchmark runner.

Runs backward asof-join benchmarks across Pandas, Polars, and Daft (native),
collecting wall time and peak RSS per run.

Usage examples:

  # All three systems, small scale, 3 timed runs:
  python -m benchmarking.asof_join --scale small

  # Specific systems:
  python -m benchmarking.asof_join --scale medium --systems polars,daft_native

  # Skip warmup (e.g. during local iteration):
  python -m benchmarking.asof_join --scale small --skip_warmup

  # Override S3 paths with local files (generated by data_generation.py):
  python -m benchmarking.asof_join --scale small --local_data_dir /tmp/asof_data
  # Expects /tmp/asof_data/small/left.parquet and /tmp/asof_data/small/right.parquet
"""

from __future__ import annotations

import argparse
import logging
import pathlib
import statistics
import subprocess
import sys
import tempfile
import time
from typing import Any

logger = logging.getLogger(__name__)

SCALE_TO_S3_PATHS: dict[str, dict[str, str]] = {
    "small": {
        "left": "s3://eventual-dev-benchmarking-fixtures/asof-join/small/left.parquet",
        "right": "s3://eventual-dev-benchmarking-fixtures/asof-join/small/right.parquet",
    },
    "medium": {
        "left": "s3://eventual-dev-benchmarking-fixtures/asof-join/medium/left.parquet",
        "right": "s3://eventual-dev-benchmarking-fixtures/asof-join/medium/right.parquet",
    },
    "large": {
        "left": "s3://eventual-dev-benchmarking-fixtures/asof-join/large/left.parquet",
        "right": "s3://eventual-dev-benchmarking-fixtures/asof-join/large/right.parquet",
    },
}

ALL_SYSTEMS = ["pandas", "polars", "daft_native"]

_MONITOR_SCRIPT = str(pathlib.Path(__file__).parent / "monitor.py")
_WORKER_SCRIPT = str(pathlib.Path(__file__).parent / "worker.py")

# How long to wait for the worker to print "ready" after init (seconds).
_WORKER_INIT_TIMEOUT = 120


def _run_system(
    system: str,
    left_path: str,
    right_path: str,
    n_runs: int,
    warmup: bool,
    results_dir: pathlib.Path,
) -> list[dict[str, Any]]:
    """Spawn one long-lived worker subprocess for `system`, run all iterations inside it.

    The worker is initialized once (library import + runner setup), then each
    run is driven by a JSON line on stdin. A single monitor.py process attaches
    for the full worker lifetime; per-run peak RSS is sliced from the monitor
    CSV using the start/end timestamps reported by the worker.
    """
    import json as _json

    mem_csv = str(results_dir / f"{system}_mem.csv")

    bench = subprocess.Popen(
        [sys.executable, _WORKER_SCRIPT, system],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        text=True,
    )
    monitor = subprocess.Popen([sys.executable, _MONITOR_SCRIPT, str(bench.pid), mem_csv])

    # Wait for the worker to finish initializing.
    deadline = time.monotonic() + _WORKER_INIT_TIMEOUT
    ready_line = ""
    while time.monotonic() < deadline:
        ready_line = bench.stdout.readline().strip()
        if ready_line:
            break
        time.sleep(0.1)

    if ready_line != "ready":
        bench.kill()
        monitor.kill()
        raise RuntimeError(f"[{system}] worker did not become ready (got: {ready_line!r})")

    cmd = _json.dumps({"left": left_path, "right": right_path}) + "\n"
    raw_results: list[dict[str, Any]] = []

    if warmup:
        labels = ["warmup"] + [f"run {i}" for i in range(1, n_runs + 1)]
    else:
        labels = [f"run {i}" for i in range(1, n_runs + 1)]

    for label in labels:
        logger.info("[%s] %s ...", system, label)
        bench.stdin.write(cmd)
        bench.stdin.flush()
        result_line = bench.stdout.readline().strip()
        try:
            result = _json.loads(result_line)
        except Exception:
            result = {"status": "error", "message": f"bad output: {result_line!r}"}
        raw_results.append(result)

    bench.stdin.write("exit\n")
    bench.stdin.flush()
    bench.wait()
    monitor.wait()

    # Read the full RSS trace once, then slice per run.
    rss_rows = _load_rss_csv(mem_csv)

    # Skip the warmup result (first entry) if we ran one.
    timed_results = raw_results[1:] if warmup else raw_results
    out: list[dict[str, Any]] = []
    for run_i, res in enumerate(timed_results, start=1):
        peak_rss = None
        if res.get("status") == "ok" and rss_rows:
            peak_rss = _peak_rss_in_window(rss_rows, res["start_ts"], res["end_ts"])
        out.append(
            {
                "run": run_i,
                "status": res.get("status", "error"),
                "wall_time_s": res.get("wall_time_s", float("nan")),
                "peak_rss_gb": peak_rss,
            }
        )
        logger.info(
            "[%s] run %d: %s  wall=%.2fs  rss=%s GB",
            system,
            run_i,
            out[-1]["status"],
            out[-1]["wall_time_s"],
            f"{peak_rss:.2f}" if peak_rss is not None else "n/a",
        )
    return out


def _load_rss_csv(csv_path: str) -> list[dict]:
    try:
        with open(csv_path) as f:
            lines = f.read().splitlines()
        if len(lines) < 2:
            return []
        keys = lines[0].split(",")
        return [dict(zip(keys, line.split(","))) for line in lines[1:] if line]
    except FileNotFoundError:
        return []


def _peak_rss_in_window(rss_rows: list[dict], start_ts: float, end_ts: float) -> float | None:
    """Return the peak RSS (GB) observed between start_ts and end_ts."""
    vals = [float(r["rss_gb"]) for r in rss_rows if start_ts <= float(r["timestamp"]) <= end_ts]
    return max(vals) if vals else None


def main() -> None:
    logging.basicConfig(level="INFO")

    parser = argparse.ArgumentParser(description="Asof-join benchmark runner.")
    parser.add_argument("--scale", choices=list(SCALE_TO_S3_PATHS), required=True)
    parser.add_argument(
        "--systems",
        default="pandas,polars,daft_native",
        help=f"Comma-separated list of systems to benchmark. Choices: {ALL_SYSTEMS}",
    )
    parser.add_argument("--n_runs", type=int, default=3, help="Number of timed runs per system (default: 3).")
    parser.add_argument("--skip_warmup", action="store_true", help="Skip the warmup run.")
    parser.add_argument(
        "--local_data_dir",
        default=None,
        help="Override S3 paths with a local directory. Expects <dir>/<scale>/left.parquet and right.parquet (matching data_generation.py output).",
    )
    args = parser.parse_args()

    systems = [s.strip() for s in args.systems.split(",")]
    for s in systems:
        if s not in ALL_SYSTEMS:
            parser.error(f"Unknown system: {s!r}. Valid choices: {ALL_SYSTEMS}")

    # Resolve data paths
    if args.local_data_dir:
        local_dir = pathlib.Path(args.local_data_dir) / args.scale
        left_path = str(local_dir / "left.parquet")
        right_path = str(local_dir / "right.parquet")
    else:
        paths = SCALE_TO_S3_PATHS[args.scale]
        left_path = paths["left"]
        right_path = paths["right"]

    logger.info("Scale: %s | Systems: %s", args.scale, systems)
    logger.info("Left:  %s", left_path)
    logger.info("Right: %s", right_path)

    results_dir = pathlib.Path(tempfile.mkdtemp(prefix="asof_join_bench_"))
    all_results: dict[str, list[dict[str, Any]]] = {}

    for system in systems:
        try:
            all_results[system] = _run_system(
                system=system,
                left_path=left_path,
                right_path=right_path,
                n_runs=args.n_runs,
                warmup=not args.skip_warmup,
                results_dir=results_dir,
            )
        except Exception as exc:
            logger.error("[%s] failed: %s", system, exc)
            all_results[system] = [
                {"run": i, "status": "error", "wall_time_s": float("nan"), "peak_rss_gb": None}
                for i in range(1, args.n_runs + 1)
            ]

    print("\n=== SUMMARY ===")
    col = {"system": 12, "scale": 8, "status": 6, "time_s": 12, "peak_gb": 12}
    header_line = (
        f"{'system':<{col['system']}} {'scale':<{col['scale']}} {'status':<{col['status']}}"
        f" {'med_time_s':>{col['time_s']}} {'med_peak_gb':>{col['peak_gb']}}"
    )
    print(header_line)
    print("-" * len(header_line))

    for system in systems:
        runs = all_results[system]
        overall_status = "ok" if any(r["status"] == "ok" for r in runs) else "error"
        ok_times = [r["wall_time_s"] for r in runs if r["status"] == "ok"]
        med_time = statistics.median(ok_times) if ok_times else float("nan")
        rss_vals = [r["peak_rss_gb"] for r in runs if r.get("peak_rss_gb") is not None]
        rss_str = f"{statistics.median(rss_vals):.2f}" if rss_vals else "n/a"
        print(
            f"{system:<{col['system']}} {args.scale:<{col['scale']}} {overall_status:<{col['status']}}"
            f" {med_time:>{col['time_s']}.2f} {rss_str:>{col['peak_gb']}}"
        )


if __name__ == "__main__":
    main()
